weni-ai/chats-webapp

.gitignore
package.json
src/components/chats/ContactInfo/Media.vue
src/components/chats/ContactInfo/index.vue
src/components/chats/FileUploader.vue
src/components/chats/MediaMessage/Controls.vue
src/components/chats/MessageEditor.vue
src/components/chats/QuickMessages/QuickMessageCard.vue
src/components/chats/QuickMessages/QuickMessageForm.vue
src/components/chats/QuickMessages/index.vue
src/components/chats/SuggestionBox.vue
src/components/chats/chat/ChatHeader.vue
src/components/chats/chat/ChatMessage.vue
src/components/chats/chat/ChatMessages.vue
src/layouts/ChatsLayout/components/TheRoomList/RoomGroup/ContactRoom.vue
src/layouts/ChatsLayout/components/TheRoomList/index.vue
src/locales/translations.json
src/plugins/i18n.js
src/views/chats/ActiveChat.vue
src/views/chats/ClosedChats.vue
yarn.lock

Create both `pt-BR` and `en-US` messages and update static messages in the source code by vue-i18n created messages

feat: Add vue-i18n messages

---

.github/workflows/build-shared-dev.yaml
src/styles/global.scss
src/styles/reset.scss

Create the "Build Chats-WebApp in Shared" workflow for the `develop` branch deployment

Create GitHub Actions WorkFlow

---

src/components/ModalOnBoardingChats.vue
src/layouts/ChatsLayout/index.vue
src/services/api/resources/settings/sector.js

Fixed the template click in the other images and put a new get to know how many sectors are by project id.

Fix: On Boarding template click and insert a new get on sector.js

---

src/components/ModalOnBoardingChats.vue
src/layouts/ChatsLayout/index.vue
src/services/api/resources/settings/sector.js

Fixed the template click in the other images and put a new get to know how many sectors are by project id.

Fixed the click on the other images of the modal

---

src/components/settings/forms/Agent.vue
src/components/settings/forms/Queue.vue
src/components/settings/forms/Sector.vue
src/components/settings/forms/Tags.vue
src/locales/translations.json
src/views/Settings/Sectors/Edit.vue
src/views/Settings/Sectors/New.vue
src/views/Settings/index.vue

Made adjustments to sector settings

Fix interface poliment

---

src/components/chats/ContactInfo/Media.vue
src/components/chats/MediaMessage/Previews/Audio.vue
src/components/settings/forms/Sector.vue
src/layouts/ChatsLayout/index.vue
src/locales/translations.json

✔Fix the layout padding on chats grid
✔Fix the font-size in audio section, sidebar of contact info
✔Validation in input-time on sector settings

Layout adjustment 

---

.github/workflows/build-shared-dev.yaml
src/components/chats/MediaMessage/Previews/Document.vue
src/components/chats/MediaMessage/index.vue
src/components/chats/chat/ChatHeader.vue
src/components/dashboard/Filters.vue
src/layouts/DashboardLayout/index.vue
src/views/chats/ActiveChat.vue

✔Fix the classifier room when change the contact without selecting the tag;
✔Function to open pdf file in the chat messages;
✔Added extension .webp to images in the chat messages;
✔Added grid giant in the dashboard layout;
✔Added rule to not show the close button when the contact is in the queue;
✔Added time referring to the time of the contact in the queue

Layout adjustments

---

src/components/settings/forms/Agent.vue
src/components/settings/forms/Sector.vue

Fix the list function of managers and agents

Fix the list function of managers and agents

---

src/components/chats/MediaMessage/index.vue
src/services/api/resources/chats/message.js

Remove the text part when user send midia on chats message.

Feat new media endpoint

---

src/components/PreferencesBar.vue
src/components/chats/ContactInfo/index.vue
src/components/chats/MediaMessage/Previews/Document.vue
src/components/chats/MediaMessage/Previews/Fullscreen.vue
src/components/chats/MediaMessage/Previews/Image.vue
src/components/chats/MediaMessage/Previews/Video.vue
src/components/chats/MediaMessage/index.vue
src/components/chats/QuickMessages/QuickMessageForm.vue
src/components/chats/QuickMessages/index.vue
src/components/chats/chat/ChatMessage.vue
src/components/chats/chat/ChatMessages.vue
src/services/api/resources/chats/contact.js
src/store/modules/rooms.js
src/views/Settings/Sectors/Edit.vue
src/views/chats/ActiveChat.vue
src/views/chats/ClosedChats.vue
src/views/profile/Preferences.vue

Fix the duplicate message
Fix save button on edit sector
Fix pagination in closed chats list
Add loading for audio files

New features and adjusments

---

src/layouts/ChatsLayout/components/TemplateMessages/index.vue

Fix new type of documents and text editor bug

---

src/App.vue

Had left some "console.log" to test in the dev environment if and when a function was called.

refactor: Removed console.logs in App.vue

---

src/App.vue

Added function call that sends user status when reconnecting with WebSocket

Persist user status when reconnect with WebSocket

---

src/components/dashboard/Filters.vue
src/services/api/resources/dashboard/dashboardManager.js

Restored buttons for exporting metrics in xls and adjusted requests that correct corrupted files

Dashboard export XLS files

---

src/components/chats/MessageEditor/TextBox.vue
src/views/chats/Home.vue

- Adjust TextBox size when adding long quick message
- Adjust TextBox size when typing long message and then delete
- Limit to one audio upload at a time
- Remove appearance of the send message button when writing only spaces

Fix new message editor

---

src/components/settings/forms/Sector.vue
src/components/settings/forms/__tests__/Sector.spec.js
src/components/settings/forms/__tests__/mocks/sectorMock.js
src/locales/translations.json
src/views/Settings/Sectors/Edit.vue
src/views/Settings/Sectors/New.vue

Added agent signature option in Chats settings

Agents signature

---

src/components/chats/MessageEditor/index.vue
src/components/chats/QuickMessages/index.vue
src/components/chats/chat/ChatMessage.vue
src/components/layouts/chats/AsideSlotTemplate/index.vue
src/layouts/ChatsLayout/components/ChatsBackground/index.vue
src/layouts/ChatsLayout/components/ChatsDropzone/index.vue
src/layouts/ChatsLayout/components/TheRoomList/index.vue
src/layouts/ChatsLayout/index.vue
src/views/Dashboard/ViewMode/index.vue
src/views/chats/ClosedChats.vue
src/views/chats/Home.vue

Reverts weni-ai/chats-webapp#316

Revert "Design review of quick messages and screen spacing with rooms"

---

src/components/chats/chat/ChatMessages.vue
src/layouts/ChatsLayout/components/TheRoomList/index.vue
src/services/api/resources/chats/message.js
src/services/api/resources/chats/room.js
src/store/modules/rooms.js
src/views/Dashboard/ViewMode/index.vue
src/views/chats/ClosedChats.vue
src/views/chats/Home.vue

Changed the paging method for endpoints for listing rooms (/room) and listing room messages (/msg).
The offset and limit option was removed and the "next" field was integrated to access the next page.

Request pagination

---

src/components/chats/chat/ChatMessage.vue

Adjusted the message when receiving an image with subtitles

Image subtitles

---

src/App.vue

Fixed the bug in the contact's "last messages" when transferring rooms

Last message as json

---

package.json
src/App.vue
src/layouts/ChatsLayout/index.vue
src/utils/notifications.js
src/views/chats/Home.vue
yarn.lock

1. Added request for permission to display notifications, using the _Iframessa_ to request the iframe host;
2. Notifying new chat messages by window notifications.

Window notifications

---

src/App.vue

Fixed bug that caused chat messages not to update

Fixed bug on websocket messages

---

src/components/chats/ContactInfo/index.vue
src/components/chats/MessageEditor/index.vue
src/components/chats/QuickMessages/QuickMessageCard.vue
src/components/chats/QuickMessages/index.vue
src/components/chats/chat/ChatMessage.vue
src/components/layouts/chats/AsideSlotTemplate/index.vue
src/components/settings/lists/ListSectorQuickMessages.vue
src/layouts/ChatsLayout/components/ChatsBackground/index.vue
src/layouts/ChatsLayout/components/ChatsDropzone/index.vue
src/layouts/ChatsLayout/components/TemplateMessages/index.vue
src/layouts/ChatsLayout/components/TheRoomList/index.vue
src/layouts/ChatsLayout/index.vue
src/views/Dashboard/ViewMode/index.vue
src/views/chats/ClosedChats.vue
src/views/chats/Home.vue

- Refactored the quick messages component in the layout
- Adjusted the behavior of quick messages opened by the preferences section to synchronize the selected message with the textbox of the opened room
- Made a new grid for the Chats layout
- Reviewed all screen spacing with rooms (open or closed)

Design review layout

---

src/layouts/ChatsLayout/index.vue

Removed position relative from ChatsLayout main

Fixed fullscreen container

---

src/components/chats/chat/ChatMessage.vue

Implementation of link handling in messages, allowing links sent and received to now be clickable and direct to their respective pages.

Treat text url function in messages text

---

package.json
src/components/TagGroup.vue
src/components/chats/MediaMessage/Previews/Document.vue
src/components/chats/MediaMessage/Previews/Video.vue
src/components/chats/MediaMessage/index.vue
src/components/chats/MessageEditor/EmojiPicker.vue
src/locales/translations.json
src/styles/global.scss
yarn.lock

**Goal:** improve the user experience when playing videos in Chats, addressing the need for standardization and cross-browser compatibility.
Currently, playing video across different browsers can result in incompatibilities and inconsistent experiences for users. To address this issue, a video player library has been introduced that will ensure a uniform experience across all major browsers.

New video player

---

src/layouts/ChatsLayout/components/FlowsTrigger/index.vue

Fixed open room alert remaining after deselecting the contact by tag

Flow trigger contact alert

---

src/components/chats/chat/ModalGetChat.vue

Added verification before call update message bulk to check room has user

Fixed update messages bulk

---

src/components/PreferencesBar.vue
src/components/chats/ContactInfo/index.vue
src/components/chats/FlowsTrigger/ModalAddNewContact.vue
src/components/chats/FlowsTrigger/SelectFlow.vue
src/components/chats/MessageManager/index.vue
src/components/chats/QuickMessages/QuickMessageForm.vue
src/components/chats/QuickMessages/index.vue
src/components/chats/chat/ChatMessages.vue
src/components/chats/chat/ModalGetChat.vue
src/components/settings/forms/Agent/Edit.vue
src/components/settings/forms/Queue/Edit.vue
src/layouts/ChatsLayout/components/FlowsTrigger/index.vue
src/layouts/ChatsLayout/index.vue
src/locales/translations.json
src/store/modules/roomMessages.js
src/views/Dashboard/ViewMode/index.vue
src/views/Settings/Sectors/Edit.vue
src/views/chats/Home.vue
src/views/chats/ModalCloseChat.vue

- Feedback for forwarding to a room has been adjusted
- Added "Chat with agent" feedback to differentiate between chat with bot
- All UnnnicButton variations have been adjusted and the use of UnnnicButtonNext has been discontinued

Fixed unnnic buttons variations and chats feedbacks

---

src/components/PreferencesBar.vue
src/components/chats/ContactInfo/index.vue
src/components/chats/FlowsTrigger/ModalAddNewContact.vue
src/components/chats/FlowsTrigger/SelectFlow.vue
src/components/chats/MessageManager/index.vue
src/components/chats/QuickMessages/QuickMessageForm.vue
src/components/chats/QuickMessages/index.vue
src/components/chats/chat/ChatMessages.vue
src/components/chats/chat/ModalGetChat.vue
src/components/settings/forms/Agent/Edit.vue
src/components/settings/forms/Queue/Edit.vue
src/layouts/ChatsLayout/components/FlowsTrigger/index.vue
src/layouts/ChatsLayout/index.vue
src/locales/translations.json
src/store/modules/roomMessages.js
src/views/Dashboard/ViewMode/index.vue
src/views/Settings/Sectors/Edit.vue
src/views/chats/Home.vue
src/views/chats/ModalCloseChat.vue

Solved: The message component was crashing when triggering the click event of a media that was not available on the first page of messaging pagination.

Chats crash when click at media not paginate

---

src/views/chats/ClosedChats/RoomsTable.vue

Adjusted room table page of pagination component in history

Fixed history pagination page

---

src/components/TagGroup.vue
src/components/chats/chat/ChatMessages.vue

Added titles to chat feedbacks and messages

Titles to chat messages

---

src/components/chats/chat/ModalGetChat.vue

**Goal**: Address issue where users are experiencing errors when trying to pick up rooms due to missing email addresses when accessing the endpoint.
**Solution**: To resolve this issue, a validation was introduced that ensures that the user's email address is available before making the call to the room reservation endpoint.

Added validation to request profile again and pass to take room

---

src/components/TablePagination.vue
src/components/chats/FlowsTrigger/ModalListTriggeredFlows.vue
src/components/chats/FlowsTrigger/SelectFlow.vue
src/layouts/ChatsLayout/components/FlowsTrigger/index.vue
src/layouts/ChatsLayout/index.vue
src/locales/translations.json
src/services/api/resources/chats/flowsTrigger.js
src/views/chats/ClosedChats/RoomsTable.vue
src/views/loadings/ClosedChats/RoomsTableLoading.vue
src/views/loadings/TablePaginationLoading.vue
src/views/loadings/TriggeredFlowsLoading.vue

**Objective**: To meet the needs of users who needed to see in general when and which flows were sent to contacts

View sent flows

---

src/components/dashboard/Filters.vue
src/components/dashboard/GeneralMetrics.vue
src/components/dashboard/TableMetrics.vue
src/components/dashboard/metrics/BySector/HistoryMetrics.vue
src/components/dashboard/metrics/General/LiveMetrics.vue
src/layouts/DashboardLayout/index.vue
src/locales/translations.json
src/views/chats/ClosedChats/RoomsTable.vue

- Improved alignment between fields and metrics
- Removed dashboard sector filter if it is unique
- Added at tag and agent fields option "none" to clear filter

Improve UI of dashboard filter fields

---

package.json
src/components/PreferencesBar.vue
src/layouts/SettingsLayout/index.vue
src/views/Dashboard/ViewMode/index.vue
src/views/Settings/Sectors/Edit.vue
src/views/chats/Home.vue
yarn.lock

**Updates:**
1. Adjusted some spacings on the app
2. Fixed preferences agent status uppercase 
3. Updated design system version

Design review

---

src/layouts/ChatsLayout/components/TheCardGroups/index.vue
src/locales/translations.json

**Updates:** Make the "without results" message in the chat search more friendly

Added new friendly message to alert lack of active chats

---

src/components/chats/MessageManager/FileUploader.vue
src/views/chats/Home/HomeModals.vue

**Updates:** Event emitted for modal controller to treat file uploader as closed and be able to open it again

Fixed open file uploader modal

---

src/App.vue
src/services/api/websocket/setup.js

**Updates:** Restoration of agent status when websocket connection is reestablished.

Fixed agent status reconnect

---

src/views/Settings/Sectors/Edit.vue

**Updates:** Fixed the duplication of agents in queue configurations

Fixed the duplication of agents in queue configurations

---

.github/pull_request_template.md

**Objective:** Make pull requests standardized and facilitate their opening.

[ENGAGE-393] Pull request template

---

src/components/dashboard/GeneralMetrics.vue

fix: Adjust the values of the metrics cards

---

src/components/dashboard/GeneralMetrics.vue

Reverts weni-ai/chats-webapp#399

Revert "fix: Adjust the values of the metrics cards"

---

src/layouts/ChatsLayout/components/FlowsTrigger/index.vue
src/layouts/ChatsLayout/components/TheCardGroups/index.vue
src/services/api/resources/flows/flowsTrigger.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Improve contact search speed when triggering flows.
- Minimum of 3 characters to request a filter;
- Increased the waiting time between characters to make the request to 1.3s;
- Fix infinite loading when an urn comes as an empty array;
- Cancellation of previous requests (from this endpoint) when performing a new search;
- Limited the size of the return on the endpoint to 10 contacts when making a filter.

Fix of search contacts at flows trigger section

---

src/components/chats/FlowsTrigger/ModalAddNewContact.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When building the branches related to chats mobile, a problem that went unnoticed by the merge was found, making it impossible for the image to be created.
Replaced unnnicAlert call used in ModalAddNewContact to function used at mobile version

Fix mobile build

---

src/components/chats/MessageManager/__tests__/SuggestionBox.spec.js
src/components/chats/MessageManager/__tests__/TextBox.spec.js
src/components/chats/__tests__/CustomField.spec.js
src/components/chats/__tests__/TagGroup.spec.js
src/components/chats/__tests__/mocks/customFieldMock.js
src/components/settings/forms/__tests__/Agent.spec.js
src/components/settings/forms/__tests__/Queue.spec.js
src/components/settings/forms/__tests__/Sector.spec.js
src/components/settings/forms/__tests__/Tags.spec.js
src/components/settings/forms/__tests__/mocks/queueMock.js
src/services/api/resources/settings/__tests__/sector.spec.js

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
In order for us to implement the modules' standard workflow, it is first necessary to fix the tests that were broken in the application.
- Fixed create queue tests
- Fixed create sector tests
- Fixed create agents at queues tests
- Fixed create tags at sectors tests
- Fixed TagGroup, TextBox, CustomField and SuggestionBox tests

[ENGAGE-583] Fix all broken tests

---

src/layouts/ChatsLayout/components/FlowsTrigger/index.vue
src/services/api/resources/flows/flowsTrigger.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
It was necessary to adjust the endpoint response to get the results

fix: Adjust the response to get the results

---

src/services/api/websocket/listeners/room/create.js
src/services/api/websocket/listeners/room/update.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When creating a room, the error `app.$route.dispatch is not a function` was logged.
Now, upon receiving this notification, the right reference (`$store` instead of `$route`) is used and the room will be created only if it does not already exist.
The existing room validation code in the update room function was also refactored.

[ENGAGE-708] - Fix of WebSocket create room function

---

src/components/settings/forms/Queue.vue
src/components/settings/forms/Sector.vue
src/components/settings/forms/Tags.vue
src/components/settings/lists/ListSectorQueues.vue
src/locales/translations.json
src/views/Settings/Sectors/Edit.vue
src/views/Settings/Sectors/New.vue
src/views/Settings/index.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Some word translations were missing.
- Added translations for some words

[ENGAGE-648] - Add missing translations

---

src/App.vue
src/registerServiceWorker.js
src/utils/notifications.js
src/views/chats/Home/index.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users need to answer contacts via mobile devices, so we decided to transform Chats into a Progressive Web App (PWA), which can be installed on devices.
Adjusted notifications API to send from the service worker if the user is accessing a mobile device.

[ENGAGE-852] - PWA notifications

---

src/App.vue
src/views/chats/Mobile/MobileHome.vue
src/views/chats/Mobile/MobileSelectOrgProject.vue
vue.config.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Users need to answer contacts via mobile devices, so we decided to transform Chats into a Progressive Web App (PWA), which can be installed on devices.
- Adjusted WebSocket connection/reconnection when choosing a project on mobile devices;
- Adjusted the scrolling of the list of rooms and discussions;
- Fixed the error "Uncaught SyntaxError: Unexpected token '<'" when installing PWA.

[ENGAGE-852] - PWA fixes

---

public/.well-known/assetlinks.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Google play store was requiring the asset links fingerprints to be updated to authenticate the app.
Updated fingerprints at assetlinks.

[ENGAGE-904] - Updated fingerprints at assetlinks

---

src/components/chats/ContactInfo/CustomField.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users would like to apply a custom field longer than 50 characters.
Changed the maxLength in custom field input to 500.

[ENGAGE-1186] - Custom field max length characters to 500

---

package.json
src/components/chats/MessageManager/__tests__/SuggestionBox.spec.js
src/components/chats/MessageManager/__tests__/TextBox.spec.js
src/components/chats/__tests__/CustomField.spec.js
src/components/chats/__tests__/ModalBulkTransfer.spec.js
src/components/chats/__tests__/RoomsTransferFields.spec.js
src/components/chats/__tests__/TagGroup.spec.js
src/components/chats/__tests__/UserAvatar.spec.js
src/components/settings/forms/__tests__/Agent.spec.js
src/components/settings/forms/__tests__/Queue.spec.js
src/components/settings/forms/__tests__/Sector.spec.js
src/components/settings/forms/__tests__/Tags.spec.js
src/components/settings/forms/__tests__/mocks/agentMock.js
src/components/settings/forms/__tests__/mocks/sectorMock.js
src/components/settings/forms/__tests__/mocks/tagsMock.js
src/services/api/resources/settings/__tests__/project.spec.js
src/services/api/resources/settings/__tests__/queue.spec.js
src/services/api/resources/settings/__tests__/sector.spec.js
vite.config.mjs
yarn.lock

* * [x] Bugfix
* * [ ] Tests
* * [x] Other
Fix tests that broke when migrating to vue 3. As jest is also not supported correctly with vite, replacing it with vitest.
* Fix broken tests
* Change jest to vitest

[ENGAGE-1201] - Fix tests

---

docker/nginx/nginx.conf

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
When carrying out tests, we discovered that our configuration defined in Nginx had several headers missing and not configured. We then decided to implement the headers for analysis and correction in order to improve our security.

Cloud 1178

---

.github/workflows/test-and-build.yml
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Get Codecov reports and metrics.
- Added coverage command and package.json scripts;
- Added get tests coverage at CI workflow.

[ENGAGE-1164] - Config tests coverage

---

src/main.js
src/plugins/Hotjar.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Monitoring by session replay using Hotjar.
Added Hotjar script at main.

[ENGAGE-1306] - Hotjar

---

src/App.vue
src/components/chats/RoomsTransferFields.vue
src/store/modules/chats/rooms.js
src/store/modules/profile.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Users were unable to complete the transfer cycle when trying to transfer a room to a queue that they were not authorized to be in.
Added validation to filter rooms that are only part of queues that the user has permission to.

[ENGAGE-1368] - Fix transfer rooms to unauthorized queues

---

src/services/api/websocket/__tests__/setup.unit.spec.js
src/services/api/websocket/__tests__/socket.unit.spec.js
src/services/api/websocket/__tests__/soundNotification.unit.spec.js
src/services/api/websocket/listeners/__tests__/listeners.unit.spec.js
src/services/api/websocket/listeners/room/__tests__/create.unit.spec.js
src/services/api/websocket/listeners/room/__tests__/delete.unit.spec.js
src/services/api/websocket/listeners/room/__tests__/update.unit.spec.js
src/services/api/websocket/listeners/status/__tests__/update.unit.spec.js
vite.config.mjs

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Increase aplication tests coverage
Added tests to Websocket files and listeners, except for the discussion and room messages listeners

[CFE-479] - Some websocket unit tests

---

src/services/api/websocket/listeners/room/message/__tests__/create.unit.spec.js
src/services/api/websocket/listeners/room/message/__tests__/update.unit.spec.js

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Increase aplication tests coverage
- Added tests of websocket room messages create and update;

[CFE-482] - Tests of websocket room messages 

---

docker/Dockerfile
docker/file_handler.sh

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Add script in posix shell to remove old files and use in Dockerfile
Implementation a posix shell script to manage and remove old files based on unix timestamps since the base image only provides posix shell. The script reads a list of timestamps, calculates which files to remove and manages this list. Modified the Dockerfile to use this script specifically for css files cleanup, providing an solution without additional dependencies.

Add script in posix shell to remove old files and use in Dockerfile

---

src/views/chats/Home/ModalCloseChat.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- add translation to secondary btn in modalDialog
- add translation

[ENGAGE-2538] Add secondary btn translation in modal close chat

---

.github/workflows/build-chats-webapp-push-tag-shared.yaml
docker/Dockerfile

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Need to add multiplatforms for different architectures.

Cloud 2169

---

src/views/Settings/SettingsProjectOptions/CustomBreakOption.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- New config to personalization status
- Add modal
- Add Form logic
- Add list Logic
- Add translations
- Add mocks
- [Design File 1](https://www.figma.com/design/q3ze1CoLGa8Att0fownmcj/Infracommerce?node-id=4335-8595&m=dev)

[ENGAGE-2716] Add custom breaks modal

---

src/views/Settings/SettingsProjectOptions/CustomBreakOption.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Improvement status customization
- Creating status component
- Adding translations
- Adding mock logic
- [Design File 1](https://www.figma.com/design/q3ze1CoLGa8Att0fownmcj/Infracommerce?node-id=4393-1188&m=dev)

[ENGAGE-2719] Status bar component

---

src/layouts/ChatsLayout/components/FooterButton/index.vue
src/layouts/ChatsLayout/components/ViewOptions/ViewButton.vue
src/layouts/ChatsLayout/components/ViewOptions/index.vue
src/layouts/ChatsLayout/components/ViewOptions/tests/ViewButton.unit.spec.js
src/layouts/ChatsLayout/components/ViewOptions/tests/ViewOptions.unit.spec.js
src/layouts/ChatsLayout/components/ViewOptions/tests/__snapshots__/ViewButton.unit.spec.js.snap
src/layouts/ChatsLayout/components/ViewOptions/tests/__snapshots__/ViewOptions.unit.spec.js.snap
src/layouts/ChatsLayout/index.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- Redesign Options chats because status pause
- add new options component
- add secondary component
- add many tests
- [Design File ](https://www.figma.com/design/q3ze1CoLGa8Att0fownmcj/Infracommerce?node-id=4335-7670&m=dev)

[ENGAGE-2718] New options to chats

---

src/services/api/resources/chats/pauseStatus.js
src/views/Settings/SettingsProjectOptions/CustomBreakOption.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- integrate endpoints
- add integrations

[ENGAGE-2722] initial Integrate back pause status

---

src/components/StatusBar.vue
src/components/__tests__/StatusBar.spec.js
src/components/__tests__/__snapshots__/StatusBar.spec.js.snap
src/views/Settings/SettingsProjectOptions/__tests__/CustomBreakOptions.unit.spec.js

* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
- improvement security and confiability components
- add more tests

[ENGAGE-2834] Add more tests infracommerce

---

package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
- upgrade unnnic to fix errors

[ENGAGE-2875] upgrade unnnic

---

package.json
src/components/settings/forms/__tests__/__snapshots__/ExtraOptions.spec.js.snap
src/views/Settings/Sectors/New/__tests__/__snapshots__/DiscartChangesModal.spec.js.snap
src/views/__tests__/__snapshots__/SectorEdit.spec.js.snap
src/views/__tests__/__snapshots__/Settings.spec.js.snap
src/views/__tests__/__snapshots__/SettingsHeader.spec.js.snap
src/views/__tests__/__snapshots__/SettingsSectors.spec.js.snap
yarn.lock

* * [ ] Bugfix
* * [ ] Tests
* * [X] Other
- FIX ci
- FIX recriate snapshots

[ENGAGE-2875] Fix/logic to recriate snapshots

---

docker/Dockerfile

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other

Fix new node version

---

src/components/StatusBar.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other

fix logic handleCloseCustom

---

src/components/StatusBar.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
fix convert days to hours
- add convert logic

fix convert days to hours

---

src/views/Settings/SettingsProjectOptions/index.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- adjust order render message

fix translation logic

---

src/components/StatusBar.vue
src/components/__tests__/StatusBar.spec.js
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/Settings/SettingsProjectOptions/CustomBreakOption.vue
src/views/Settings/SettingsProjectOptions/__tests__/CustomBreakOptions.unit.spec.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- In some situations, chats were not updating changes made to the settings
- add localstorage logic

[ENGAGE-3117] logic chats update if new config

---

src/locales/es.json

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- change 'discapacitada' to 'desactivada'
- change 'discapacitada' to 'desactivada'

[ENGAGE-3159] change translations ES

---

.github/workflows/build-chats-webapp-push-tag-shared.yaml

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Changing the workflow so that it becomes reusable and simpler to implement

Cloud 2342

---

src/components/settings/forms/General.vue

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- Improve experience in select managers
- adjusting default mode

[ENGAGE-3694] add logic to set default after addSectorManager

---

src/components/StatusBar.vue
src/components/__tests__/StatusBar.spec.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- improve logic to status open to prevent double click
- add toggling logic
- add tests

[ENGAGE-3762] Add prevent logic status menu open

---

src/components/StatusBar.vue
src/services/api/resources/chats/pauseStatus.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- remove uncessary error in sentry
- Add logic to remove erro sentry in custom_status 404

[ENGAGE-3756] Remove errors sentry

---

package.json
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/chats/ClosedChats/RoomsTable.vue
src/views/chats/ClosedChats/RoomsTableFilters.vue
src/views/chats/ClosedChats/__tests__/ClosedChats.spec.js
src/views/chats/ClosedChats/__tests__/RoomsTable.spec.js
src/views/chats/ClosedChats/__tests__/RoomsTableFilters.spec.js
src/views/chats/ClosedChats/index.vue
yarn.lock

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Improve performance filters
- add logic to reduce filter range to máx 90 days

[ENGAGE-3709] - Reduce filter range history

---

src/services/api/resources/chats/__tests__/media.unit.spec.js
src/services/api/resources/chats/__tests__/message.unit.spec.js
src/services/api/resources/chats/__tests__/pauseStatus.unit.spec.js
src/services/api/resources/chats/pauseStatus.js

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- increasing test coverage
- improve security
- add messages tests
- add pauseStatus tests
- add room tests

[ENGAGE-3876] Increasing test coverage

---

src/components/chats/ContactInfo/Media.vue
src/components/chats/ContactInfo/__tests__/Media.spec.js
src/components/dashboard/metrics/ByAgent/HistoryMetrics.vue
src/components/dashboard/metrics/ByAgent/LiveMetrics.vue
src/components/dashboard/metrics/ByAgent/__tests__/HistoryMetrics.spec.js
src/components/dashboard/metrics/ByAgent/__tests__/LiveMetrics.spec.js
src/components/dashboard/metrics/BySector/HistoryMetrics.vue
src/components/dashboard/metrics/BySector/LiveMetrics.vue
src/components/dashboard/metrics/BySector/__tests__/HistoryMetrics.spec.js
src/components/dashboard/metrics/BySector/__tests__/LiveMetrics.spec.js
src/components/dashboard/metrics/General/LiveMetrics.vue
src/components/dashboard/metrics/General/__tests__/LiveMetrics.spec.js
src/services/__tests__/keycloak.spec.js
src/services/api/resources/settings/__tests__/group.spec.js

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- Improve coverage
- add more tests with media

[ENGAGE-4055] Add more tests chats to improve coverage

---

src/components/StatusBar.vue
src/services/api/resources/chats/__tests__/pauseStatus.unit.spec.js
src/services/api/resources/chats/pauseStatus.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- resolve problem with status online/offline
- add new param for last_status endpoint

[ENGAGE-4394] Add project UUID to last status endpoint

---

src/components/chats/ContactInfo/ModalStartDiscussion.vue
src/store/modules/chats/discussions.js

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- Add manual increment to discussion create with modal
- add manual increment discussion modal

[ENGAGE-4399] Fix logic disscussion

---

src/components/StatusBar.vue
src/layouts/ChatsLayout/components/TheCardGroups/CardGroup/index.vue

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- remove duplicate
- remove duplicate

[ENGAGE-4401] Remove UnnnicDisclaimer component from CardGroup in ChatsLayout

---

src/components/chats/Mobile/ProjectSelector.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
add clickable
- add clickable to project card

[ENGAGE-4410] feat: add placeholder text and logging to ProjectSelector component

---

src/layouts/ChatsLayout/components/TheCardGroups/CardGroup/RoomCard.vue
src/layouts/ChatsLayout/components/TheCardGroups/CardGroup/index.vue
src/services/api/websocket/listeners/room/create.js
src/store/modules/config.js
src/views/chats/Home/HomeChat.vue

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- Remove condition automatic rounting queue
- Remove condition automatic rounting queue

[ENGAGE-4415] Remove condition automatic rounting queue

---

src/components/chats/ContactInfo/ProtocolText.vue
src/components/chats/ContactInfo/index.vue
src/layouts/ChatsLayout/components/TheCardGroups/index.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/chats/ClosedChats/RoomsTableFilters.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Improve logic to contact protocol
- add new translations
- add new logic to contact protocol
- [Design File](https://www.figma.com/design/MOFNxVZLaOFJ1xI1445Atf/Human-service-2025?node-id=613-1589&m=dev)

[ENGAGE-4353] New logic for contact protocol

---

src/components/chats/FlowsTrigger/ModalAddNewContact.vue
src/components/chats/FlowsTrigger/SelectFlow.vue
src/components/chats/FlowsTrigger/SelectProjects.vue
src/components/chats/FlowsTrigger/SendFlow.vue
src/components/chats/FlowsTrigger/SendFlowButton.vue
src/components/chats/FlowsTrigger/__tests__/ModalAddNewContact.spec.js
src/components/chats/FlowsTrigger/__tests__/SelectFlow.spec.js
src/layouts/ChatsLayout/components/FlowsTrigger/index.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/services/api/resources/chats/flowsTrigger.js
src/services/api/resources/flows/flowsTrigger.js
src/utils/__tests__/requests.spec.js
src/utils/requests.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- invert logic to select flow after select contacts in principal projects
- adjust all logic flows-trigerred
- adjust many endpoints to suport new projects

[ENGAGE-4720] Invert flows trigger logic to principal projects

---

src/components/chats/chat/ModalGetChat.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json

* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
add feedback user when api error
- add feedback user when api error
- add translate

[ENGAGE-4796] Hotfix logic modal get chat

---

src/App.vue
src/services/api/resources/featureFlag/__tests__/featureFlag.spec.js
src/services/api/resources/featureFlag/featureFlag.js
src/store/modules/__tests__/featureFlag.spec.js
src/store/modules/featureFlag.js

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- add global logic to use feature flag in chats
- add feature flag endpoint
- add feature flag global store
- add feature flag tests
- add feature flag load in App

[ENGAGE-4657] Add global feature flag logic
