src/layouts/ChatsLayout/index.vue
It had to be removed because it has a permission conflict
=> removed temporarily banner on boarding

package-lock.json, package.json, src/components/PreferencesBar.vue, src/components/chats/ContactInfo/Media.vue, src/components/chats/ContactInfo/index.vue, src/components/chats/QuickMessages/index.vue, src/components/chats/chat/ChatHeader.vue, src/components/chats/chat/ChatMessages.vue, src/components/settings/forms/Agent.vue, src/components/settings/forms/Agent/Edit.vue, src/components/settings/forms/Queue.vue, src/components/settings/forms/Queue/Edit.vue, src/components/settings/forms/Sector.vue, src/components/settings/forms/Tags.vue, src/layouts/ChatsLayout/components/TheRoomList/RoomGroup/ContactRoom.vue, src/layouts/ChatsLayout/components/TheRoomList/index.vue, src/locales/translations.json, src/services/api/resources/settings/sector.js, src/views/Settings/Sectors/Edit.vue, src/views/Settings/index.vue, src/views/chats/ActiveChat.vue, src/views/chats/ClosedChats.vue
Field select user
Put width in the tooltips component
Put the names in alphabetic order on select manager and agent
Change the layout of save and delete button in the queue configuration
when a new queue is add, open the layout for add agents
Modal for confirmation of delete the queue
Fix the button of the queue because is was appearing in the sector part
Fixed the alert of saving the new configurations on sector e remove the redirecting part  
Fixed the margin of scroll in the list of sectors and sector configuration
=> Layout adjusments

src/App.vue
The connection with the WebSocket closes when there is some instability in the server, but the front was not able to open the connection again. The old code tried to reconnect when catching 'catch' after sending 'ping' failed, but it didn't. Basically, the logic failure occurs when the method of sending 'ping' fails and, as it is asynchronous, it does not interrupt the flow, it just displays an error message on the console, so it would never fall into the 'catch'.
Better explanation in this thread: https://stackoverflow.com/questions/31002592/javascript-doesnt-catch-error-in-websocket-instantiation
Now, instead of waiting for the error to happen, a validation is performed to check the status of the connection with the WebSocket and if it is closed, it tries to reconnect.
=> WS reconnection when connection is closed

src/components/settings/forms/Queue.vue, src/views/Settings/Sectors/Edit.vue
On the settings page, the quick message field on the queues tab was removed and the breadcrumb was added when entering a queue edit.
=> Breadcrumb in queue configuration and automatic message field removed

src/components/chats/MediaMessage/Previews/Fullscreen.vue, src/components/chats/chat/ChatMessages.vue
Added a button to download the images available in the chat.
- The treatedUrl function is necessary so that the url coming from the image is treated and returned as one that can be fetched directly from the frontend.
- The `a` element was not used for download, since the images in s3 do not have the header _Content-Disposition: attachment;_, which makes it impossible to download directly.
=> Download images

src/components/dashboard/TableMetrics.vue
Fixed the crash in dashboard that occurred when trying to filter a sector that had agents with the same names. 
The problem was in passing the key, which previously differentiated by name and was adjusted to differentiate by email
=>  Fixed table metrics for key

src/components/chats/MessageEditor/SuggestionBox.vue
Fixed crash when shotcurts were opened and there were many duplicate keys
=> Adjusted the shortcut for keys to uuids

package.json, src/components/ModalOnBoardingChats.vue, src/components/chats/ContactInfo/CustomField.vue, src/components/chats/MediaMessage/Controls.vue, src/components/chats/MessageEditor/TextBox.vue, src/components/chats/MessageEditor/index.vue, src/components/chats/QuickMessages/QuickMessageForm.vue, src/components/chats/TemplateMessages/LayoutTemplateMessage.vue, src/components/chats/UserAvatar.vue, src/components/chats/chat/ChatMessage.vue, src/components/chats/chat/ChatMessages.vue, src/components/dashboard/Filters.vue, src/components/dashboard/metrics/BySector/HistoryMetrics.vue, src/components/settings/forms/Agent.vue, src/components/settings/forms/Queue.vue, src/components/settings/forms/Sector.vue, src/layouts/ChatsLayout/components/TheRoomList/RoomGroup/ContactRoom.vue, src/locales/translations.json, src/views/Settings/Sectors/New.vue, yarn.lock
Most selects used in Chats have been switched to the new "SelectSmart" component, including:
- Filter by agent on the Dashboard
- Filter by tag on the Dashboard
- Addition of manager in sector creation/edit
- Addition of agents in the creation/editing of sector queues
=> Change old selects to SelectSmart

src/components/chats/MediaMessage/index.vue
**Solved**: When a geolocation message is received in the chat, it was empty, because the message had not been previously handled.
=> Added geolocation media message variation

src/components/chats/chat/ChatMessages.vue, src/views/chats/ClosedChats.vue
The functionality responsible for maintaining the scroll in the message, ensuring that it remains at the end, was presenting problems in the chat history due to a function that inadvertently added a value of 15 pixels during the pagination process.
=> Fix of scroll to bottom when paginate in closed chats

src/components/TagGroup.vue
Adjusted line break in tags with flex prop, to ensure users can view all added tags properly.
=> Tags line break 

src/store/modules/roomMessages.js
**Goal**: Maintain the integrity of messages and ensure they are displayed in the correct rooms.
**Solution**: In the previous code, validation was being done based on the activeRoom constant, which no longer reflected the current value of the active room variable. As a result, messages were being associated with the wrong rooms. To solve this problem, I updated the code so that validation is done directly with the activeRoom.uuid property of Rooms.state. Messages are now correctly compared to the active room, ensuring they are in the correct room.
=> Fixed integrity of messages in rooms

src/layouts/ChatsLayout/components/TheRoomList/RoomGroup/ContactRoom.vue
**Issue**: The contacts component with unread messages was not loaded because the way i18n language was configured between Chats and Unnnic were different.
=> Passed the locale from 'en' to Unnnic instead of 'en-us' in ContactRoom component

src/components/chats/FlowsTrigger/ModalAddNewContact.vue
It was necessary to add a cell phone mask in the add new contact field, as WhatsApp now accepts this type of data.
An array of masks was added, so that either telephone or cell phone numbers could be accepted.
Mask for a telephone:
Mask for a cell phone:
=> feat: New contact input mask

src/services/api/websocket/listeners/room/update.js
The sound when receiving a chat by a agent or the chat being sent to a queue should be a different sound. Maintaining the standard sound.
Logic was added so that a type of sound would be emitted when transferring or forwarding a chat.
<br />
=> fix: Sound of transferring or forwarding a chat

src/services/api/websocket/listeners/room/update.js, src/store/modules/chats/rooms.js, src/views/chats/Home/index.vue
Users were reporting that more than one agent was able to answer the same room.
The function that redirects to the home screen when the active room is transferred has been adjusted. Furthermore, along with the redirection to the home screen, the room is reset if the owner is no longer the user or is no longer on hold.
=> [ENGAGE-424] - Fixed redirection to home and removal of room when it is transferred

src/services/api/resources/settings/sector.js, src/views/Settings/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
If users had more than 20 sectors, they were unable to see the next sectors.
A feature was added that when there are more than 20 sectors, a new sector page with a limit of 20 is created from the request. It is possible to view the new sectors while scrolling to the end of the page.
=> feat: Load more sectors when scroll to bottom on page Settings

src/components/chats/ContactInfo/index.vue, src/router/routes/chats.js, src/views/chats/ClosedChats/RoomsTable.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The redirect button for contact history was not working as it should after the history restructuring and users were missing it.
The functionality of history filters to receive the query params of the route was added and with this the button to redirect the contact's history makes a push passing the contact's urn as the query param (resulting in the filter only of the histories of that contact).
https://github.com/weni-ai/chats-webapp/assets/69015179/bb598c2e-70b8-48c4-b15a-15fc155e3de5
=> Fixed contact info tab redirect to history

src/components/chats/ContactInfo/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users complained that the chat's custom fields were not appearing in the history after the room was closed.
Validations for showing custom fields only in active chats have been removed.
=> [ENGAGE-572] - Added the listing of custom fields in closed chats

src/components/chats/ContactInfo/index.vue, src/locales/translations.json, src/views/chats/ClosedChats/RoomsTable.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
The protocol number was required because in some cases in a flow it is necessary to have a protocol number and make it visible in the contact information.
- A functionality has been added that gets this protocol number
- The protocol was added in the html but so that it will only be visible if there really is a number
- The style was changed so that when there is a protocol number it is grouped with the contact number
- Some translations have been added
- The history search placeholder has been changed
- A title was added when hovering the mouse over the contact in the history
- [Design File …
=> [ENGAGE-568] - Add the protocol number in the contact info

src/components/chats/FlowsTrigger/ModalAddNewContact.vue, src/locales/translations.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
When we add a new contact but enter a phone number that has already been used, no feedback appears on the screen.
- Added a function that checks the response from the endpoint, and if there is already a contact with the same phone number, an alert will appear on the screen.
- Added translation for alert text
- [Design File 1](https://www.figma.com/file/05cXobrT3hSvqZyQc3DuFn/Disparo-de-fluxos?type=design&node-id=1725-24115&mode=design&t=RrDY9UBBaV9Fy8R4-0)
=> [ENGAGE-603] - Alert if there is already a contact with the same number

src/components/chats/ContactInfo/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
The contact transfer session had some inconsistencies for the UX.
- Changed the type of transfer button to the primary
- Added check to disable the transfer button if the transfer option is not already selected
- Adjusted spacing between radio and queue/agent select buttons
- [Design with adjustments to the contact transfer design](https://www.figma.com/file/EKDuFFZYBOXei5BNzGCQyB/Redesign-Chats?type=design&node-id=2854%3A10199&mode=design&t=LbFGlPfAkuz7BRmZ-1)
=> Fix UX of contact info transfer section

src/components/dashboard/Filters.vue, src/services/api/resources/settings/sector.js, src/views/Settings/index.vue, src/views/chats/ClosedChats/RoomsTableFilters.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The listing of sectors in the dashboard and chat history selects was limited to 20 items (backend default), while it is not possible to add pagination, an increase in this limit became necessary.
- Refactored list sectors requisition and added limit param;
- Adjusted limit of sector listing requests that are listed in selects.
=> [ENGAGE-641] - Fix sector list limit

src/layouts/ChatsLayout/components/FlowsTrigger/index.vue, src/services/api/resources/flows/flowsTrigger.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The first requests for listing contacts when triggering flows were sending the old token, generating the 401 http code. Also, users without urns were being listed.
- Adjusted the token sent in the first contact list request;
- Corrected the name of the computed variable "letras" to the English standard;
- Removed the list of users without URN.
=> Fixes of flows trigger contacts

src/components/dashboard/metrics/BySector/HistoryMetrics.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users with many agents missed listing ordering to improve the search for agents.
Added the function that orders project agents by status and alphabetically
=> [ENGAGE-769] - Order dashboard agent chats by status and alphabetically

src/components/chats/ContactInfo/CustomField.vue, src/components/chats/__tests__/CustomField.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Users missed a redirection to the link that was exposed as a non-editable custom field.
- Added anchor to custom fields non-editables if are a url
- Added test to anchor at custom field
- Refactored CustomField component
=> [ENGAGE-824] - Redirectable non-editable custom fields

src/router/index.js, src/views/chats/ClosedChats/RoomsTable.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users feel the need to open room histories in a new tab.
- Encapsulated see history button into an anchor.
https://github.com/weni-ai/chats-webapp/assets/69015179/e7f2120a-d316-4ab2-893f-22dc8a4734fb
=> [ENGAGE-1195] - Change the view room history button to a link to open in a new tab

src/components/chats/chat/ChatFeedback.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When setting a custom field with many characters, the feedback went beyond the room container, preventing the user from closing the room and accessing the contact information.
Added text overflow ellipsis at chat feedback.
=> [ENGAGE-1219] - Added text overflow ellipsis at chat feedback

src/router/routes/dashboard.js, src/views/Dashboard/Manager/index.vue, src/views/Dashboard/ViewMode/index.vue, src/views/chats/ClosedChats/RoomsTable.vue, src/views/chats/ClosedChats/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users complained that when changing routes on the dashboard and in the room history, the filter applied to these views was reset.
- Replaced v-if with v-show to remain the mounted history view;
- Centralized the dashboard and view mode route in one component and used the same logic as above.
=> [ENGAGE-1206] - Persistence of views filters

src/App.vue, src/components/PreferencesBar.vue, src/components/chats/Mobile/ModalPreferences.vue, src/services/api/websocket/listeners/status/update.js, src/services/api/websocket/setup.js, src/services/api/websocket/soundNotification.js, src/services/keycloak.js, src/store/modules/config.js, src/utils/config.js, src/utils/nilo.js, src/views/onboarding/Agent.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Users could not use two applications at the same time because when they opened a new application, the old one took the project and the token from the new one, due to storage sharing because we used localStorage logic.
Changed all localStorage code to sessionStorage, which keeps the storage divided between tabs.
=> [ENGAGE-1216] - Fix switching projects when opening a new tab

src/components/PreferencesBar.vue, src/components/chats/Mobile/ModalPreferences.vue, src/services/api/websocket/soundNotification.js, src/utils/config.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
With the project changing to sessionStorage, when opening the history in a new tab, the user was unable to make requests because sessionStorage handles data by tab.
- Used localStorage again for the project, but as an alternative to sessionStorage;
- `PREFERENCES_SOUND` has also been turned to localStorage for a better user experience.
=> [ENGAGE-1270] - Fix opening history in new tab

src/components/chats/MessageManager/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Users were unable to see the send files and audio buttons.
- Changed the default data for prop loadingFileValue to null;
- Added validator for loadingFileValue prop.
=> [ENGAGE-1273] - Hotfix loading bar and send button without visible file

src/components/chats/RoomsTransferFields.vue, src/components/chats/__tests__/RoomsTransferFields.spec.js, src/locales/translations.json, src/views/Settings/index.vue
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Managers needed a feature to block the transfer of rooms to offline users. With the opportunity, we also added the disclaimer to notify when the transfer is allowed, informing that the user is offline.
- Added tests to verify this at RoomsTransferFields.spec.js;
- Added disclaimer to inform if no contact is online or to inform that the user selected for the transfer is offline;
- Added config at project to enable and disable this feature.
- [Transfer rooms disclaimers and config to block transfers to offline agents](https://www.figma.com/design/acYQeQACRxh3bXmniwYbwI/Bloquear-transfer%C3%AAncia-para-agente-offline?nod …
=> [ENGAGE-1244] - Transfer rooms disclaimers

src/locales/translations.json
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Users were confused about whether the blocking setting for offline agents was active or inactive.
- Replaced translation block transfer to offline agents.
=> [ENGAGE-1244] - Fix of text in the transfer blocking configuration for offline agents

src/views/chats/ClosedChats/RoomsTable.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Users needed an IU improvement where they could not see the full name of contact in the history of this column in the table.
- Changed to `display: grid` Table Row Stylization, separating the columns to improve the IU.
=> [ENGAGE-1260] - Fix RoomsTable columns size

src/router/index.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When the user token expired with chats being used as an iframe in connect, the module redirected to keycloak, which cannot be used within an iframe, thus generating an error when loading the module in connect.
- Added validation to only call keycloak routes if is mobile.
=> [ENGAGE-1373] - Fix keycloak redirect at desktop devices

docker/Dockerfile, docker/nginx/nginx.conf
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Disable http method if not GET in nginx, as requested by compliance.
Modify the nginx config file to limit_except to deny all requests to respond 403 to all requests made by non GET method.
=> Disable http method if not GET in nginx

src/components/StatusBar.vue, src/components/__tests__/StatusBar.spec.js, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add new feedback alert to users
- adjust status bar to use new alerts
- [Design File 1](https://www.figma.com/design/q3ze1CoLGa8Att0fownmcj/Infracommerce?node-id=4827-777&m=dev)
=> [ENGAGE-2960] Add new toasts to status bar

src/components/chats/chat/ChatMessages/__tests__/ChatMessages.spec.js, src/components/chats/chat/ChatMessages/index.vue, src/services/api/websocket/listeners/room/message/changeStatus.js, src/store/modules/chats/roomMessages.js, src/utils/messages.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Adjustment to support new message read status indication format and improvements
- Removed roomMessagesStatusMapper from state management.
- Updated message status logic to use is_read and is_delivered flags.
- Simplified updateMessageStatus function to directly modify message properties.
- Adjusted tests to reflect changes in message status handling.
=> [ENGAGE-4212] - Update message status handling in ChatMessages component and related services

src/services/api/websocket/setup.js
- Added a new method to calculate reconnect delay using exponential backoff with random jitter to improve connection stability.
- Introduced a maximum reconnect delay to prevent excessive wait times.
- Reset reconnect attempts counter upon successful connection to ensure proper delay calculation on subsequent failures.
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
feat: implement exponential backoff for WebSocket reconnections
adjst setup
=> feat: implement exponential backoff for WebSocket reconnections
